-- db.session.execute("""INSERT INTO questions
--   (question_id, question)
-- VALUES
--   (1,'Question 1: Define Goods and services. (2 marks)'),
--   (1,'Question 2: Define a Business. (2 marks) '),
--   (1,'Question 3:  Why is it important for Air Vigour PLC remain profitable to their stakeholders? (3 marks) '),
--   (1,'Question 4: Who are the most important stakeholders to Air Vigour and explain why? (6 marks) '),
--   (1,'Question 5: Discuss the importance of having a clear business of objective in a changing environment? (9 marks) '),
--   (2,'Question 1: What is the meaning of Objectives? (2 marks) '),
--   (2,'Question 2: Give me two types of objectives? (2 marks) '),
--   (2,'Question 3: From the Case Study, get one objective that Omar has set and explain why that objective is a good or bad one. (3 marks) '),
--   (2,'Question 4: Explain one reason why businesses change their objectives? (3 marks)  '),
--   (2,'Question 5: List one stakeholder and explain their purpose in Omar’s business. (4 marks) '),
--   (2,'Question 6: What are the two advantages of setting objectives in Omar’s case? (6 marks) '),
--   (2,'Question 7: Discuss whether Omar’s objective stated below is a good objective:\n"From today onwards until the start of Ramadan we shall focus only on making the business survive." (9 marks)'),
--   (3,'Question 1: Define multinational companies. (2 marks)'),
--   (3,'Question 2: Define AGM (2 marks)'),
--   (3,'Question 3: Provide reasons for why Rafid is wanting to diversify his business? (3 marks)'),
--   (3,'Question 4: What are the advantages of having multinationals to an economy? (6 marks) '),
--   (3,'Question 5: What are the disadvantages of having multinationals to other business in the country? (6 marks) '),
--   (3,'Question 6: Rafid has plans in making Chickeny Tendor as private limited company and franchise his business outside KSA.\n Choice 1: Chickeny Tendor becoming a Limited Liability company.\nChoice 2: Chickeny Tndor becoming a Franchise.\n Choose from the option above and justify why you chose that option. (10 marks)'),
--   (4,'Question 1: Define a Public enterprise. (2 marks) '),
--   (4,'Question 2: Define the deed of partnership. (2 marks) '),
--   (4,'Question 3: Explain 3 advantage of being in a partnership. (6 marks) '),
--   (4,'Question 4: Explain 3 disadvantages of being in a partnership. (6 marks) '),
--   (4,'Question 5: Discuss whether Lawyer Trunk should remain as a law firm or shift its ownership in becoming a private limited company. (9 marks) '),
--   (5,'Question 1: Define a franchisee '),
--   (5,'Question 2: Define a franchisor '),
--   (5,'Question 3: What are the advantages and the disadvantages of being a franchisor '),
--   (5,'Question 4: What are the advantages and the disadvantages of being a franchisee '),
--   (5,'Question 5: Discuss whether James should become open a franchisee in the middle of a populated city in UK? (9 marks) '),
--   (5,'Question 6: What are the effects of franchises to the people and the economy of developing countries, i.e India? (12 marks) '),
--   (6,'Question 1: By what percentage did the sales decrease from 2012 to 2016? (1 mark) '),
--   (6,'Question 2: Define primary market? (2 marks) '),
--   (6,'Question 3: Why has there been a decline in the primary sector? (3 marks) '),
--   (6,'Question 4: How has industrialisation effected Cobalt Mineral LTD from the beginning to the present. (3 marks) '),
--   (6,'Question 5: The Australian government has a bill which shall impact the environmentally unfriendly procedures that the mining businesses are doing in the quarries.  \nHow shall Cobalt Mineral LTD get effected if this bill gets passed? (9 marks)"'),
--   (6,'Question 6: Discuss whether the board of directors should change to public limited corporation. (10 marks) '),
--   (7,'Question 1: Define a prospectus. '),
--   (7,'Question 2: Define a public limited company.  '),
--   (7,'Question 3: Explain the advantages of Olivia and Olivia PLC being a public limited company. (6 marks) '),
--   (7,'Question 4: Explain the disadvantages of Olivia and Olivia PLC being a public limited company. (6 marks) '),
--   (7,'Question 5: Discuss the advantages of Olivia and Olivia PLC becoming a private limited company on the internal stakeholders. (9 marks) '),
--   (8,'Question 1: Define Public Corporation. (2 marks) '),
--   (8,'Question 2: Define Monopoly. (2 marks) '),
--   (8,'Question 3: Give one advantage of Public Corporations? (3 marks) '),
--   (8,'Question 4: Give two disadvantages of Public Corporations? (6 marks) '),
--   (8,'Question 5: Why do governments Privatise certain industries? (9 marks) '),
--   (9,'Question 1: Which sector is Florencia’s business is in? (1 mark) '),
--   (9,'Question 2: Key 3 factors which determines which form of business ownership? (3 marks) '),
--   (9,'Question 3: What are the key reasons why Florencia wants to remain as a Sole Trader? (3 marks) '),
--   (9,'Question 4: What are the issues for being a sole trader? (6 marks) '),
--   (9,'Question 5: Why is it important to choose the appropriate form of business ownership? (9 marks) '),
--   (9,'Question 6: If Florencia wished, which of the following types of business ownership is best for Florencia to choose from?\nOption 1: Partnership\nOption 2: Private limited company\nJustify your choice from the option above. (10 marks)'),
--   (10,'Question 1: Define the primary industry. (2 marks) '),
--   (10,'Question 2: Define the secondary industry. (2 marks) '),
--   (10,'Question 3: Define the Tertiary industry. (2 marks) '),
--   (10,'Question 4: Describe the change in the primary industry between the 1770 to 2002. Give two reasons for such a difference. (6 marks) '),
--   (10,'Question 5: Describe the change in the secondary and tertiary industry between the 1770 to 2002. Give two reasons for such a difference. (6 marks) '),
--   (10,'Question 6: Discuss the change in the interdependence between primary, secondary and tertiary with the influence of industrialisation and deindustrialisation. (12 marks) '),
--   (11,'No Questions'),
--   (11,'No Questions'),
--   (11,'No Questions'),
--   (11,'No Questions'),
--   (12,'Question 1: Define pressure groups. (2 marks) '),
--   (12,'Question 2: How has International trade benefited businesses? (3 marks) '),
--   (12,'Question 3: What are the key factors in which companies must keep in mind when selling their goods and services overseas? (6 marks) '),
--   (12,'Question 4: What are the advantages of trade blocs (such as NATO and the European Union)? (6 marks) '),
--   (12,'Question 5: Discuss the potential dangers of Globalisation? (10 marks) '),
--   (13,'Question 1: Define Multinationals. (2 marks) '),
--   (13,'Question 2: What are the advantages of having a multinational company in a country. '),
--   (13,'Question 3: What are the dangers of multinational companies to countries. (6 marks) '),
--   (13,'Question 4: The benefits of being a multinational company. (9 marks)'),
--   (14,'NOT DONE'),
--   (14,'NOT DONE'),
--   (14,'NOT DONE'),
--   (14,'NOT DONE'),
--   (14,'NOT DONE'),
--   (15,'Question 1: Define the primary industry. (2 marks) '),
--   (15,'Question 2: Define the secondary industry. (2 marks) '),
--   (15,'Question 3: Define the Tertiary industry. (2 marks) '),
--   (15,'Question 4: Describe the change in the primary industry between the 1770 to 2002. Give two reasons for such a difference. (6 marks) '),
--   (15,'Question 5: Describe the change in the secondary and tertiary industry between the 1770 to 2002. Give two reasons for such a difference. (6 marks) '),
--   (15,'Question 6: Discuss the change in the interdependence between primary, secondary and tertiary with the influence of industrialisation and deindustrialisation. (12 marks) ');"""
--                    )

CREATE TABLE questions (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  question_id INT,
  question TEXT
);
INSERT INTO questions
  (question_id, question)
VALUES
  (1,'Question 1: Define Goods and services. (2 marks)'),
  (1,'Question 2: Define a Business. (2 marks) '),
  (1,'Question 3:  Why is it important for Air Vigour PLC remain profitable to their stakeholders? (3 marks) '),
  (1,'Question 4: Who are the most important stakeholders to Air Vigour and explain why? (6 marks) '),
  (1,'Question 5: Discuss the importance of having a clear business of objective in a changing environment? (9 marks) '),
  (2,'Question 1: What is the meaning of Objectives? (2 marks) '),
  (2,'Question 2: Give me two types of objectives? (2 marks) '),
  (2,'Question 3: From the Case Study, get one objective that Omar has set and explain why that objective is a good or bad one. (3 marks) '),
  (2,'Question 4: Explain one reason why businesses change their objectives? (3 marks)  '),
  (2,'Question 5: List one stakeholder and explain their purpose in Omar’s business. (4 marks) '),
  (2,'Question 6: What are the two advantages of setting objectives in Omar’s case? (6 marks) '),
  (2,'Question 7: Discuss whether Omar’s objective stated below is a good objective:\n"From today onwards until the start of Ramadan we shall focus only on making the business survive." (9 marks)'),
  (3,'Question 1: Define multinational companies. (2 marks)'),
  (3,'Question 2: Define AGM (2 marks)'),
  (3,'Question 3: Provide reasons for why Rafid is wanting to diversify his business? (3 marks)'),
  (3,'Question 4: What are the advantages of having multinationals to an economy? (6 marks) '),
  (3,'Question 5: What are the disadvantages of having multinationals to other business in the country? (6 marks) '),
  (3,'Question 6: Rafid has plans in making Chickeny Tendor as private limited company and franchise his business outside KSA.\n Choice 1: Chickeny Tendor becoming a Limited Liability company.\nChoice 2: Chickeny Tndor becoming a Franchise.\n Choose from the option above and justify why you chose that option. (10 marks)'),
  (4,'Question 1: Define a Public enterprise. (2 marks) '),
  (4,'Question 2: Define the deed of partnership. (2 marks) '),
  (4,'Question 3: Explain 3 advantage of being in a partnership. (6 marks) '),
  (4,'Question 4: Explain 3 disadvantages of being in a partnership. (6 marks) '),
  (4,'Question 5: Discuss whether Lawyer Trunk should remain as a law firm or shift its ownership in becoming a private limited company. (9 marks) '),
  (5,'Question 1: Define a franchisee '),
  (5,'Question 2: Define a franchisor '),
  (5,'Question 3: What are the advantages and the disadvantages of being a franchisor '),
  (5,'Question 4: What are the advantages and the disadvantages of being a franchisee '),
  (5,'Question 5: Discuss whether James should become open a franchisee in the middle of a populated city in UK? (9 marks) '),
  (5,'Question 6: What are the effects of franchises to the people and the economy of developing countries, i.e India? (12 marks) '),
  (6,'Question 1: By what percentage did the sales decrease from 2012 to 2016? (1 mark) '),
  (6,'Question 2: Define primary market? (2 marks) '),
  (6,'Question 3: Why has there been a decline in the primary sector? (3 marks) '),
  (6,'Question 4: How has industrialisation effected Cobalt Mineral LTD from the beginning to the present. (3 marks) '),
  (6,'Question 5: The Australian government has a bill which shall impact the environmentally unfriendly procedures that the mining businesses are doing in the quarries.  \nHow shall Cobalt Mineral LTD get effected if this bill gets passed? (9 marks)"'),
  (6,'Question 6: Discuss whether the board of directors should change to public limited corporation. (10 marks) '),
  (7,'Question 1: Define a prospectus. '),
  (7,'Question 2: Define a public limited company.  '),
  (7,'Question 3: Explain the advantages of Olivia and Olivia PLC being a public limited company. (6 marks) '),
  (7,'Question 4: Explain the disadvantages of Olivia and Olivia PLC being a public limited company. (6 marks) '),
  (7,'Question 5: Discuss the advantages of Olivia and Olivia PLC becoming a private limited company on the internal stakeholders. (9 marks) '),
  (8,'Question 1: Define Public Corporation. (2 marks) '),
  (8,'Question 2: Define Monopoly. (2 marks) '),
  (8,'Question 3: Give one advantage of Public Corporations? (3 marks) '),
  (8,'Question 4: Give two disadvantages of Public Corporations? (6 marks) '),
  (8,'Question 5: Why do governments Privatise certain industries? (9 marks) '),
  (9,'Question 1: Which sector is Florencia’s business is in? (1 mark) '),
  (9,'Question 2: Key 3 factors which determines which form of business ownership? (3 marks) '),
  (9,'Question 3: What are the key reasons why Florencia wants to remain as a Sole Trader? (3 marks) '),
  (9,'Question 4: What are the issues for being a sole trader? (6 marks) '),
  (9,'Question 5: Why is it important to choose the appropriate form of business ownership? (9 marks) '),
  (9,'Question 6: If Florencia wished, which of the following types of business ownership is best for Florencia to choose from?\nOption 1: Partnership\nOption 2: Private limited company\nJustify your choice from the option above. (10 marks)'),
  (10,'Question 1: Define the primary industry. (2 marks) '),
  (10,'Question 2: Define the secondary industry. (2 marks) '),
  (10,'Question 3: Define the Tertiary industry. (2 marks) '),
  (10,'Question 4: Describe the change in the primary industry between the 1770 to 2002. Give two reasons for such a difference. (6 marks) '),
  (10,'Question 5: Describe the change in the secondary and tertiary industry between the 1770 to 2002. Give two reasons for such a difference. (6 marks) '),
  (10,'Question 6: Discuss the change in the interdependence between primary, secondary and tertiary with the influence of industrialisation and deindustrialisation. (12 marks) '),
  (11,'No Questions'),
  (11,'No Questions'),
  (11,'No Questions'),
  (11,'No Questions'),
  (12,'Question 1: Define pressure groups. (2 marks) '),
  (12,'Question 2: How has International trade benefited businesses? (3 marks) '),
  (12,'Question 3: What are the key factors in which companies must keep in mind when selling their goods and services overseas? (6 marks) '),
  (12,'Question 4: What are the advantages of trade blocs (such as NATO and the European Union)? (6 marks) '),
  (12,'Question 5: Discuss the potential dangers of Globalisation? (10 marks) '),
  (13,'Question 1: Define Multinationals. (2 marks) '),
  (13,'Question 2: What are the advantages of having a multinational company in a country. '),
  (13,'Question 3: What are the dangers of multinational companies to countries. (6 marks) '),
  (13,'Question 4: The benefits of being a multinational company. (9 marks)'),
  (14,'NOT DONE'),
  (14,'NOT DONE'),
  (14,'NOT DONE'),
  (14,'NOT DONE'),
  (14,'NOT DONE'),
  (15,'Question 1: Define the primary industry. (2 marks) '),
  (15,'Question 2: Define the secondary industry. (2 marks) '),
  (15,'Question 3: Define the Tertiary industry. (2 marks) '),
  (15,'Question 4: Describe the change in the primary industry between the 1770 to 2002. Give two reasons for such a difference. (6 marks) '),
  (15,'Question 5: Describe the change in the secondary and tertiary industry between the 1770 to 2002. Give two reasons for such a difference. (6 marks) '),
  (15,'Question 6: Discuss the change in the interdependence between primary, secondary and tertiary with the influence of industrialisation and deindustrialisation. (12 marks) ');